[package]
name = "hydrant-server"
description = "The hydrant service binary"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
rust-version.workspace = true
publish = false

[[bin]]
name = "hydrant"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
axum = { workspace = true }
clap = { workspace = true }
figment = { workspace = true }
hydrant-api = { workspace = true }
hydrant-core = { workspace = true }
hydrant-store = { workspace = true }
metrics = { workspace = true }
metrics-exporter-prometheus = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_yaml_ng = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "signal", "net"] }
tower-http = { workspace = true, features = ["trace", "compression-gzip", "cors", "timeout"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
figment = { workspace = true, features = ["test"] }
